"""empty message

Revision ID: d597bdb7c790
Revises: 
Create Date: 2020-05-13 16:55:49.538960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd597bdb7c790'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_depart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_depart_title'), 'table_depart', ['title'], unique=True)
    op.create_table('table_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('table_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_name', sa.String(length=32), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('statue', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('table_sort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_sort_title'), 'table_sort', ['title'], unique=False)
    op.create_table('table_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['table_sort.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_brand_title'), 'table_brand', ['title'], unique=False)
    op.create_table('table_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['table_menu.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['table_permission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('url')
    )
    op.create_table('table_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('telephone', sa.String(length=11), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('did', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['did'], ['table_depart.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_index(op.f('ix_table_user_name'), 'table_user', ['name'], unique=True)
    op.create_table('table_adders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adder', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('tele', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['table_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_adders_name'), 'table_adders', ['name'], unique=False)
    op.create_table('table_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('picture', sa.String(length=225), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['table_brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_goods_title'), 'table_goods', ['title'], unique=False)
    op.create_table('table_role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['table_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['table_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['table_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['table_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gid'], ['table_goods.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['table_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_cart_name'), 'table_cart', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_cart_name'), table_name='table_cart')
    op.drop_table('table_cart')
    op.drop_table('table_user_role')
    op.drop_table('table_role_permission')
    op.drop_index(op.f('ix_table_goods_title'), table_name='table_goods')
    op.drop_table('table_goods')
    op.drop_index(op.f('ix_table_adders_name'), table_name='table_adders')
    op.drop_table('table_adders')
    op.drop_index(op.f('ix_table_user_name'), table_name='table_user')
    op.drop_table('table_user')
    op.drop_table('table_permission')
    op.drop_index(op.f('ix_table_brand_title'), table_name='table_brand')
    op.drop_table('table_brand')
    op.drop_index(op.f('ix_table_sort_title'), table_name='table_sort')
    op.drop_table('table_sort')
    op.drop_table('table_role')
    op.drop_table('table_order')
    op.drop_table('table_menu')
    op.drop_index(op.f('ix_table_depart_title'), table_name='table_depart')
    op.drop_table('table_depart')
    # ### end Alembic commands ###
